/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ru.spbu.strukov.UiInterface;

import java.awt.BorderLayout;
import java.lang.reflect.InvocationTargetException;

/**
 * Created on 30 янв. 2022 г. 17:27:33
 * @author Alexander Mikhailovich Kovshov
 */
public class MainFrame extends javax.swing.JFrame {
    
    private AboutBox aboutBox;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        onContentPanel.add(new MainPanel(), BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onContentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileStartMenuItem = new javax.swing.JMenuItem();
        fileExitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpAboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        onContentPanel.setBackground(new java.awt.Color(242, 240, 249));
        onContentPanel.setLayout(new BorderLayout());

        fileMenu.setText("File");

        fileStartMenuItem.setText("Start");
        fileStartMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileStartMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileStartMenuItem);

        fileExitMenuItem.setText("Exit");
        fileExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileExitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        helpAboutMenuItem.setText("About");
        helpAboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpAboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(onContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fileExitMenuItemActionPerformed

    private void fileStartMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileStartMenuItemActionPerformed
        ru.spbu.strukov.Coalition.setCount(0);
        ru.spbu.strukov.Game.main(null);
    }//GEN-LAST:event_fileStartMenuItemActionPerformed

    private void helpAboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAboutMenuItemActionPerformed
        if(aboutBox == null) {
            aboutBox = new AboutBox(this, true);
            aboutBox.setLocationRelativeTo(this);
            aboutBox.setIconImages(this.getIconImages());
        }
        aboutBox.setVisible(true);
    }//GEN-LAST:event_helpAboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
                java.awt.Dimension scrSize = toolkit.getScreenSize();
                MainFrame wa = new MainFrame();
               java.awt.Dimension frSize = wa.getPreferredSize();
                wa.setBounds((scrSize.width - frSize.width) / 2,
                        (scrSize.height - frSize.height) / 2,
                        frSize.width, frSize.height);
                if (System.getProperty("os.name").startsWith("Mac")) {
                    try {
                        java.awt.Image icon = new javax.swing.ImageIcon(getClass().getResource("resources/efgLabel.png")).getImage();
                        Class appleApplicationClass = Class.forName("com.apple.eawt.Application");
                        Object appleApplication = appleApplicationClass.getMethod("getApplication", (Class<?>[]) null).invoke(null, (Object[]) null);
                        appleApplicationClass.getMethod("setDockIconImage", java.awt.Image.class).invoke(appleApplication, icon);
                    } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                    }
                } else {
                    java.util.List<java.awt.Image> icons = new java.util.ArrayList(8);
                    icons.add(toolkit.getImage(getClass().getResource("resources/efgLabel64.png")));
                    icons.add(toolkit.getImage(getClass().getResource("resources/efgLabel32.png")));
                    icons.add(toolkit.getImage(getClass().getResource("resources/efgLabel16.png")));
                    wa.setIconImages(icons);
                }
                 wa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fileExitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileStartMenuItem;
    private javax.swing.JMenuItem helpAboutMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel onContentPanel;
    // End of variables declaration//GEN-END:variables

}
